build and push emulator image:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  when: manual
  script:
    - docker-compose -f ./docker-compose.yml build
    - docker-compose -f ./docker-compose.yml push

test build:
  image: golang
  variables:
    TEST: "build-local"
  script:
    - go version
    - go build .
    - go test -v ./...

test build xgo linux:
  image: karalabe/xgo-latest
  script:
    - go version
    - go get github.com/karalabe/xgo
    - cd release/linux
    - make all

test build xgo windows:
  image: karalabe/xgo-latest
  script:
    - go version
    - go get github.com/karalabe/xgo
    - cd release/windows
    - make all

test build xgo macos:
  image: karalabe/xgo-latest
  script:
    - go version
    - go get github.com/karalabe/xgo
    - cd release/macos
    - make all

prebuíld lint:
  variables:
    TEST: "golangci"
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.0
    - golangci-lint run
#    - env: TEST=version-check
#      script:
#        - diff -u VERSION <(grep "var version = " trezord.go | cut -f 2 -d '"')
